### ISSUE TITLE
Please tell me where to insert tags?

### ISSUE THREAD

**Issue by Ved-un** [arch-anes/randwall#1]
Thanks a lot for the program!

Please tell me where to insert **tags** into the configuration file config.json ?

`{
  "api_key": "",
  "categories": {
    "anime": true,
    "general": true,
    "people": true
  },
  "exclude": [
    "microsoft",
    "logo"
  ],
  "include": [],
  "interval": 3600,
  "max_page": 500,
  "purity": {
    "nsfw": false,
    "sfw": true,
    "sketchy": false
  }`

**Comment by abelfodil** [comment]
Hello, you can use "exclude" key to exclude tags and "include" to include tags.

Thank you for your feedback, I will create a readme to document all the parameters soon!

**Comment by abelfodil** [comment]
Also I encourage you to use the latest version of the program (0.1.7), it contains many bug fixes.

**Comment by Ved-un** [comment]
Got it. Thank you very much!
